export const ROLES = {
  OWNER: 'Owner',
  ADMIN: 'Admin',
  MANAGER: 'Manager',
  STAFF: 'Staff',
  VIEWER: 'Viewer'
};

export const PERMISSIONS = {
  INVOICES_READ: 'invoices:read',
  INVOICES_CREATE: 'invoices:create',
  INVOICES_EDIT: 'invoices:edit',
  INVOICES_DELETE: 'invoices:delete',
  
  CHALLANS_READ: 'challans:read',
  CHALLANS_CREATE: 'challans:create',
  CHALLANS_EDIT: 'challans:edit',
  
  QUOTATIONS_READ: 'quotations:read',
  QUOTATIONS_CREATE: 'quotations:create',
  QUOTATIONS_CONVERT: 'quotations:convert',
  
  CUSTOMERS_READ: 'customers:read',
  CUSTOMERS_MANAGE: 'customers:manage',
  
  PRODUCTS_READ: 'products:read',
  PRODUCTS_MANAGE: 'products:manage',
  
  REPORTS_VIEW: 'reports:view',
  SETTINGS_MANAGE: 'settings:manage',
  USERS_MANAGE: 'users:manage'
};

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.MANAGER]: [
    PERMISSIONS.INVOICES_READ, PERMISSIONS.INVOICES_CREATE, PERMISSIONS.INVOICES_EDIT,
    PERMISSIONS.CHALLANS_READ, PERMISSIONS.CHALLANS_CREATE, PERMISSIONS.CHALLANS_EDIT,
    PERMISSIONS.QUOTATIONS_READ, PERMISSIONS.QUOTATIONS_CREATE, PERMISSIONS.QUOTATIONS_CONVERT,
    PERMISSIONS.CUSTOMERS_READ, PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.REPORTS_VIEW
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.INVOICES_READ, PERMISSIONS.CHALLANS_READ, PERMISSIONS.CHALLANS_CREATE,
    PERMISSIONS.QUOTATIONS_READ, PERMISSIONS.CUSTOMERS_READ, PERMISSIONS.PRODUCTS_READ
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.INVOICES_READ, PERMISSIONS.CHALLANS_READ, PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.CUSTOMERS_READ, PERMISSIONS.PRODUCTS_READ, PERMISSIONS.REPORTS_VIEW
  ]
};
